name: version-and-tag-ci

# this workflow versions and tags the merged commit using commit comments and/or mergebranch nameing. 
on:
  pull_request:
    types: [closed]

jobs:
  # This workflow contains a single job called "version-and-tag"
  version-and-tag:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mr Version
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        id: mrversion
        uses: PenCue/mrversion@bootstrap
        with:
          stable-branch: main
          int-branch: int
          dev-branch: dev
          stable-tag: null
          int-tag: rc
          dev-tag: unstable
          version-prefix: v
          initialize: YES 

      # Runs a set of commands using the runners shell
      - name: Set Tag
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true 
        run: |
          echo Full ${{ steps.mrversion.outputs.full-version }}
          git tag -f ${{ steps.mrversion.outputs.full-version }} $GIT_SHA
          git push --delete origin ${{ steps.mrversion.outputs.full-version }} || true
          git push origin --tags ${{ steps.mrversion.outputs.full-version }} 
          echo -n 
          echo Major Minor ${{ steps.mrversion.outputs.major-minor-version }}
          git tag -f ${{ steps.mrversion.outputs.major-minor-version }} $GIT_SHA 
          git push --delete origin ${{ steps.mrversion.outputs.major-minor-version }} || true
          git push origin --tags ${{ steps.mrversion.outputs.major-minor-version }} 
          echo -n
          echo Major ${{ steps.mrversion.outputs.major-version }}
          git tag -f ${{ steps.mrversion.outputs.major-version }} $GIT_SHA  
          git push --delete origin ${{ steps.mrversion.outputs.major-version }} || true
          git push origin --tags ${{ steps.mrversion.outputs.major-version }} 
